---
booktitle: Proceedings of The 14th International Conference on Grammatical Inference
  2018
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
shortname: ICGI
volume: 93
year: '2019'
start: 2018-09-05
end: 2018-09-07
published: 2019-02-04
url: https://proceedings.mlr.press
author:
  name: PMLR
location: !binary |-
  V3JvY8WCYXcsIFBvbGFuZA==
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: ICGI-2018
month: 0
cycles: false
bibtex_editor: Unold, Olgierd and Dyrka, Witold and Wieczorek, Wojciech
editor:
- given: Olgierd
  family: Unold
- given: Witold
  family: Dyrka
- given: Wojciech
  family: Wieczorek
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 14th International Conference on Grammatical Inference on 05-07 September 2018

  Published as Volume 93 by the Proceedings of Machine Learning Research on 04 February 2019.

  Volume Edited by:
    Olgierd Unold
    Witold Dyrka
    Wojciech Wieczorek

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: feb
baseurl: "/v93"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
permalink: "/:title.html"
ghub:
  edit: true
  repository: v93
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: International Conference on Grammatical Inference
  url: 
  location: ''
  dates:
  - 2018-09-05
  - 2018-09-06
  - 2018-09-07
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
